import { readdirSync, statSync, writeFileSync } from 'fs';
import { join, posix } from 'path';

const DIST = 'dist';
const SW_PATH = join(DIST, 'sw.js');

// Recursively collect all files in dist/, excluding sw.js itself
function collectFiles(dir, base = '') {
  const entries = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const rel = base ? `${base}/${name}` : name;
    if (statSync(full).isDirectory()) {
      entries.push(...collectFiles(full, rel));
    } else if (rel !== 'sw.js') {
      entries.push('/' + rel.split('\\').join('/'));
    }
  }
  return entries;
}

const files = collectFiles(DIST);
const cacheVersion = `workout-${Date.now()}`;

const sw = `// Auto-generated by generate-sw.js — do not edit
const CACHE_NAME = '${cacheVersion}';

const PRECACHE_URLS = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  if (!request.url.startsWith(self.location.origin)) return;

  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) {
          // Return cached, but update in background
          fetch(request).then((response) => {
            caches.open(CACHE_NAME).then((cache) => cache.put(request, response));
          }).catch(() => {});
          return cached;
        }
        return fetch(request).then((response) => {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
          return response;
        }).catch(() => caches.match('/index.html'));
      })
    );
    return;
  }

  // Static assets (hashed filenames = immutable): cache-first
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        const clone = response.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
        return response;
      });
    })
  );
});
`;

writeFileSync(SW_PATH, sw);
console.log(`Generated ${SW_PATH} with ${files.length} precached files (${cacheVersion})`);
